# Generated by Django 3.2 on 2021-07-23 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('privateCommunity', '0004_auto_20210720_1951'),
        ('privateCommunity', '0007_auto_20210723_0239'),
    ]

    operations = [
    ]
