# Generated by Django 3.2 on 2021-07-23 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('privateCommunity', '0007_notification_post_id'),
        ('privateCommunity', '0008_merge_0004_auto_20210720_1951_0007_auto_20210723_0239'),
    ]

    operations = [
    ]
